FROM reg.ishopex.cn/paiops-lang-base/nodejs-alpine:14.21.3
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk --no-cache add ca-certificates tzdata

WORKDIR /app

COPY . .

ENV HOST 0.0.0.0
EXPOSE 3000
CMD ["npm", "start"]
