export { default as SpMiniCart } from './mini-cart'
export { default as SpForm } from './sp-form'
export { default as SpFormItem } from './sp-form-item'

export { default as SpToast } from './toast'

export { default as SpRadio } from './sp-radio'
export { default as SpRadioGroup } from './radio-group'

export { default as SpCollapse } from './collapse'
export { default as SpModal, SpModalPlugin } from './sp-modal'
export { default as SpMessage, SpMessagePlugin } from './message'
export { default as SpLabel } from './label'
export { default as SpNumInput } from './num-input'
export { default as SpPointNumPoint } from './sp-point-num-input'

export { default as SpSelect } from './sp-select'

export { default as SpImg } from './sp-img'
export { default as SpItemPromo } from './item-promo'
export { default as SpLoading, SpLoadingPlugin, SpLoadingDirective } from './sp-loading'
export { default as SpLayer } from './layer'
export { default as SpDpTransition } from './sp-dptransition'
export { default as SpTimer } from './timer'
export { default as SpStaffBadge } from './staff-badge'
export { SpFloatMenu, SpFloatMenuItem, SpFloatMenuInfo } from './float-menu'
export { default as SpSocialShare } from './social-share'
// export { SpWidgetPanel, SpWidget } from '../widgets'
export { default as SkuSelector } from './sku-selector'
export { default as SkuPointSelector } from './sku-point-selector'

export { default as SpGoodsItem } from './goods-item'
export { default as SpTipMessage } from './tip-message'
export { default as SpAddressPicker } from './address-picker'
export { default as SpAlert } from './alert'
export { default as SpGoodsRecommend } from './goods-recommend'
export { default as SpLink } from './link'
export { default as SpAnalytics } from './analytics'

export { default as SpButton } from './sp-button'
export { default as SpRate } from './rate'

export { default as SpBreadCrumb } from './sp-breadcrumb'
export { default as SpSearch } from './sp-search'
export { default as SpInput } from './sp-input'
export { default as SpPagination } from './sp-pagination'
export { default as SpPrice } from './sp-price'
export { default as SpSteps } from './steps'
export { default as SpHeader } from './sp-header'
export { default as SpFooter } from './sp-footer'
export { default as AuthHeader } from './auth-header'

export { default as Film } from './template/film'
export { default as Heading } from './template/film'
export { default as Slider } from './template/slider'
export { default as Writing } from './template/writing'

export { default as PointTag } from './point-tag'
export { default as PointPrice } from './point-price'
export { default as SpPointPrice } from './sp-point-price'
export { default as SpDatePicker } from './sp-datepicker'
export { default as SpFastBuy } from './sp-fastbuy'
export { default as SpGoodsCard } from './sp-goods-card'
export { default as SpScrollLoading } from './sp-scroll-loading'
export { default as SpGoodsInfo } from './sp-goods-info'
export { default as SpSkuPicker } from './sp-sku-picker'
export { default as SpPhotoZoom } from './sp-photo-zoom'
export { default as SpBtnPicker } from './sp-btn-picker'
export { default as SpBtnPickerGroup } from './sp-btn-picker-group'
